### PR TITLE
feat: f01 initial pull

### PR DESCRIPTION
**Pull request by nathantew14**
## Describe your changes
Frontend:
1. Added a general purpose infinite-scrolling component with optional caching, scroll position retention, and refresh timeout time option, `GrowableScroll`.
2. Added gyms tab, gyms search, and gyms detail page, which contains the "about" info and a "beta" tab with gyms beta.

Backend:
1. Added gym groups table and updated existing gyms table with information for the gym page (address, area, instagram and website URLs).
2. Added the API endpoints for the new gym search.
3. Added $afterFind to gyms model to add icon and banner image S3 URLs
4. Added web scraping for opening hours when gym details are fetched

Note: had to commit new backend lockfile for the new packages for web scraping

## Checklist before requesting a review

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by therizhao** [comment]
@nathantew14  Ping me when ready to review

**Comment by nathantew14** [comment]
@therizhao all checks passed, I just had to move the seed file for the new "gym_groups" table I made to the front by prefixing it with 00. I also updated the seed file for gyms to contain all the new info but it wasn't actually necessary, not sure if you guys want that.

**Comment by therizhao** [comment]
ok will be checking this week

**Comment by therizhao** [comment]
havent taken a detailed look. you can push to dev, which will auto-deploy the frontend to dev.climbjios-app.pages.dev/
to see if there's any issue. Note that there is no code pipeline setup to deploy the backend. You have to do it manually.

**Review by therizhao — APPROVED** [review]

**Pull request merged**
